name: build & push app image

on:
  push:
    branches: ["release"]
    paths:
      - "app/**"
      - "components/**"
      - "lib/**"
      - "prisma/**"
      - "public/**"
      - "README.md"
      - "components.json"
      - "middleware.ts"
      - "prisma.config.ts"
      - "docker-compose.yml"

jobs:
  build-fastapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build nextjs app image
        run: docker build . --file Dockerfile --tag gfwx/quicksilver-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: push fastapi image to docker hub
        run: docker push gfwx/quicksilver-app:latest
