name: docker optimised multi-image CI

on:
  push:
    branches: ["release"]
    paths: ["."]

jobs:
  build-fastapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build fastapi image
        run: docker build ./ai --file ai/Dockerfile --tag gfwx/quicksilver-ai:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: push fastapi image to docker hub
        run: docker push gfwx/quicksilver-ai:latest
