name: docker optimised multi-image CI 

on:
  push:
    branches: ["release"]
    paths: "./nginx"

jobs:
  build-nginx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build custom nginx image
        run: docker build ./nginx --file nginx/Dockerfile --tag gfwx/quicksilver-nginx
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }} 
      - name: push custom nginx image to docker hub
        run: docker push gfwx/quicksilver-nginx:latest

      
