name: build & push fastapi image

on:
  push:
    branches: ["release"]
    paths:
      - "ai/**"
      - "docker-compose.yml"

jobs:
  build-nginx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build custom fastapi image
        run: docker build ./ai --file ai/Dockerfile --tag gfwx/quicksilver-ai:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: push custom nginx image to docker hub
        run: docker push gfwx/quicksilver-ai:latest
